language: python
python: 3.8

before_install:
  - pip install --upgrade pip
  
script:
   - python3 -m pytest /test
   - coverage run -m pytest
   - coverage report

after_success:
  - pip install coveralls
  - coveralls
