language: python
python:
- "3.9"

before_install:
  - pip install --upgrade pip

script:
   - python -m pytest -s -v -rs tests/
   - coverage run -m pytest
   - coverage report

after_success:
  - pip install coveralls
  - coveralls
  
  
