language: python
python:
- "3.9"

before_install:
  - pip install --upgrade pip

install: 
  - pip install -r requirements.txt
  
script:
   - python3 -m pytest /test
   - coverage run -m pytest
   - coverage report

after_success:
  - pip install coveralls
  - coveralls
