language: python
python: 2.7
before_install:
  - pip install --upgrade pip
  
script:
   - python -m pytest /test
   - coverage run -m pytest
   - coverage report

after_success:
  - pip install coveralls
  - coveralls
