language: python
python: 3.8

before_install:
  - sudo apt-get update
  - sudo apt-get install python3
  - sudo apt-get install python-pip
  - pip install pytest
  
script:
   - python -m pytest /test
   - coverage run -m pytest
   - coverage report

after_success:
  - pip install coveralls
  - coveralls
